import React, { useState } from 'react';
import './Reports.css';

const INITIAL_REPORTS = [
  {
    id: 'rep-001',
    title: 'Weekly SOC2 Compliance Audit',
    date: '2026-02-28',
    status: 'Ready',
    size: '12 KB',
    type: 'JSON'
  },
  {
    id: 'rep-002',
    title: 'Monthly CI/CD Risk Assessment',
    date: '2026-02-01',
    status: 'Ready',
    size: '4 KB',
    type: 'JSON'
  },
  {
    id: 'rep-003',
    title: 'Q1 Vulnerability Scan Results',
    date: '2026-01-15',
    status: 'Archived',
    size: '12.8 MB',
    type: 'CSV'
  },
  {
    id: 'rep-004',
    title: 'Blockchain Audit Trail Export',
    date: '2026-02-27',
    status: 'Ready',
    size: '1.1 MB',
    type: 'JSON'
  }
];

const Reports = ({ addNotification }) => {
  const [reports, setReports] = useState(INITIAL_REPORTS);
  const [downloading, setDownloading] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    setIsGenerating(true);
    addNotification('Started new report generation task...', 'info');

    setTimeout(() => {
      const newReportId = `rep-${Math.floor(Math.random() * 900) + 100}`;
      const newReport = {
        id: newReportId,
        title: 'Ad-hoc Security & Compliance Scan',
        date: new Date().toISOString().split('T')[0],
        status: 'Ready',
        size: `${(Math.random() * 5 + 1).toFixed(1)} MB`,
        type: 'PDF'
      };

      setReports(prev => [newReport, ...prev]);
      setIsGenerating(false);
      addNotification(`Report ${newReportId} generated successfully.`, 'success');
    }, 2500);
  };

  const handleDownload = (id) => {
    setDownloading(id);
    addNotification('Preparing report file for download...', 'info');

    setTimeout(() => {
      const reportMeta = reports.find(r => r.id === id) || { type: 'JSON' };
      const extension = reportMeta.type.toLowerCase();

      let fileContent = '';
      let mimeType = 'text/plain;charset=utf-8';

      if (extension === 'json') {
        fileContent = JSON.stringify({ reportId: id, metadata: reportMeta, generatedBy: 'DevOps Shield', status: 'PASS' }, null, 2);
        mimeType = 'application/json';
      } else if (extension === 'csv') {
        fileContent = `Report ID,Title,Date,Status\n${id},"${reportMeta.title}",${reportMeta.date},${reportMeta.status}`;
        mimeType = 'text/csv;charset=utf-8;';
      } else {
        fileContent = `This is a generated ${extension} report for: ${id}\n\nGenerated by DevOps Shield.`;
      }

      const blob = new Blob([fileContent], { type: mimeType });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `report-${id}.${extension}`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setDownloading(null);
      addNotification('Report downloaded successfully.', 'success');
    }, 1500);
  };

  return (
    <div className="page reports-page">
      <header className="page-header">
        <div>
          <h1>Reports & Exports</h1>
          <p className="page-subtitle">Generate, view, and export compliance and security reports.</p>
        </div>
        <button
          className={`btn-primary enhance-hover ${isGenerating ? 'loading' : ''}`}
          onClick={handleGenerate}
          disabled={isGenerating}
        >
          {isGenerating ? (
            <span className="spinner">⚙️ Generating...</span>
          ) : (
            <><span className="btn-icon">➕</span> Generate New Report</>
          )}
        </button>
      </header>

      <section className="reports-grid">
        <div className="card overview-card reports-stat">
          <div className="stat-icon svg-icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
              <polyline points="14 2 14 8 20 8"></polyline>
              <line x1="16" y1="13" x2="8" y2="13"></line>
              <line x1="16" y1="17" x2="8" y2="17"></line>
              <polyline points="10 9 9 9 8 9"></polyline>
            </svg>
          </div>
          <div>
            <h3>{reports.length}</h3>
            <p className="muted">Reports Generated (Total)</p>
          </div>
        </div>
        <div className="card overview-card reports-stat">
          <div className="stat-icon svg-icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
              <polyline points="9 12 11 14 15 10"></polyline>
            </svg>
          </div>
          <div>
            <h3>100%</h3>
            <p className="muted">Compliance Score</p>
          </div>
        </div>
        <div className="card overview-card reports-stat">
          <div className="stat-icon svg-icon">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"></circle>
              <polyline points="12 6 12 12 16 14"></polyline>
            </svg>
          </div>
          <div>
            <h3>Scheduled</h3>
            <p className="muted">Next auto-run in 2 days</p>
          </div>
        </div>
      </section>

      <section className="card reports-table-card">
        <div className="card-header">
          <h2>Recent Reports</h2>
          <div className="table-actions">
            <button
              className="btn-outline"
              onClick={() => addNotification('Advanced filters opened', 'info')}
            >Filter</button>
          </div>
        </div>
        <div className="table-responsive">
          <table className="devops-table">
            <thead>
              <tr>
                <th>Report Title</th>
                <th>Date Generated</th>
                <th>Status</th>
                <th>Size</th>
                <th>Format</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.map(report => (
                <tr key={report.id}>
                  <td>
                    <strong>{report.title}</strong>
                  </td>
                  <td>{report.date}</td>
                  <td>
                    <span className={`badge badge-${report.status === 'Ready' ? 'success' : 'idle'}`}>
                      {report.status}
                    </span>
                  </td>
                  <td className="muted">{report.size}</td>
                  <td>
                    <span className="type-badge">{report.type}</span>
                  </td>
                  <td>
                    <button
                      className={`btn-outline download-btn ${downloading === report.id ? 'downloading' : ''}`}
                      onClick={() => handleDownload(report.id)}
                      disabled={downloading === report.id}
                    >
                      {downloading === report.id ? 'Downloading...' : 'Download'}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </div>
  );
};

export default Reports;
